In [24]:
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv") 
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:
X = heart_disease.drop("target", axis = 1)  
y = heart_disease["target"]

In [9]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [38]:
from sklearn.ensemble import RandomForestClassifier  
clf = RandomForestClassifier(n_estimators=100) 

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [39]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2) 
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
131,49,0,1,134,271,0,1,162,0,0.0,1,0,2
150,66,1,0,160,228,0,0,138,0,2.3,2,0,1
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2
35,46,0,2,142,177,0,0,160,1,1.4,0,0,2
145,70,1,1,156,245,0,0,143,0,0.0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,52,1,1,120,325,0,1,172,0,0.2,2,0,2
87,46,1,1,101,197,1,1,156,0,0.0,2,0,3
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2
221,55,1,0,140,217,0,1,111,1,5.6,0,0,3

In [40]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [41]:
y_preds = clf.predict(X_test) 
y_preds

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0])

In [42]:
y_test

195    0
187    0
8      1
32     1
203    0
      ..
152    1
24     1
224    0
103    1
213    0
Name: target, Length: 61, dtype: int64

In [43]:
clf.score(X_train, y_train)

1.0

In [44]:
clf.score(X_test,y_test)

0.7377049180327869

In [45]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.72      0.72      0.72        29
           1       0.75      0.75      0.75        32

    accuracy                           0.74        61
   macro avg       0.74      0.74      0.74        61
weighted avg       0.74      0.74      0.74        61

In [46]:
confusion_matrix(y_test, y_preds)

array([[21,  8],
       [ 8, 24]])

In [51]:
accuracy_score(y_test, y_preds)

0.7377049180327869

In [52]:
np.random.seed(42)    
for i in range(10,100,10):  
    print("Trying model with {i} estimators...")  
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train) 
    print(f"Model accurary on test set: {clf.score(X_test, y_test) * 100}%")
    print("")

Trying model with {i} estimators...
Model accurary on test set: 83.60655737704919%

Trying model with {i} estimators...
Model accurary on test set: 80.32786885245902%

Trying model with {i} estimators...
Model accurary on test set: 75.40983606557377%

Trying model with {i} estimators...
Model accurary on test set: 77.04918032786885%

Trying model with {i} estimators...
Model accurary on test set: 73.77049180327869%

Trying model with {i} estimators...
Model accurary on test set: 78.68852459016394%

Trying model with {i} estimators...
Model accurary on test set: 78.68852459016394%

Trying model with {i} estimators...
Model accurary on test set: 75.40983606557377%

Trying model with {i} estimators...
Model accurary on test set: 75.40983606557377%

In [48]:
import pickle  
pickle.dump(clf, open("random_forest_model1_1.pkl", "wb"))

In [49]:
loaded_model = pickle.load(open("random_forest_model1_1.pkl", "rb"))

In [50]:
loaded_model.score(X_test, y_test)

0.7377049180327869